---
# Handlers del rol SSH

- name: "Obtener PID de sshd"
  ansible.builtin.command: >
    docker exec {{ contenedores.ssh.nombre }} pgrep sshd
  register: sshd_pid
  changed_when: false
  listen: "Recargar SSH"

- name: "Recargar configuración SSH con kill -HUP"
  ansible.builtin.command: >
    docker exec {{ contenedores.ssh.nombre }}
    kill -HUP {{ sshd_pid.stdout_lines[0] }}
  changed_when: true
  listen: "Recargar SSH"

- name: "Reiniciar rsyslog en ssh01"
  ansible.builtin.shell: |
    docker exec {{ contenedores.ssh.nombre }} bash -c "pkill -9 rsyslogd; sleep 1; rm -f /run/rsyslogd.pid; rsyslogd"
  changed_when: true
  listen: "Reiniciar rsyslog SSH"
