#!/usr/sbin/nft -f
flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        iif "lo" accept
        ct state established,related accept
        icmp type echo-request accept
        ip saddr 192.168.100.0/24 tcp dport 22 accept
        reject with icmp type admin-prohibited
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
        ct state established,related accept

        # LAN → WAN: tráfico interno sale a internet
        ip saddr 192.168.100.0/24 ip daddr != 172.21.0.0/24 accept

        # LAN → DMZ: clientes LAN pueden acceder a proxy01
        ip saddr 192.168.100.0/24 ip daddr 172.21.0.10 tcp dport { 80, 443 } accept

        # WAN → DMZ: solo proxy01 en puertos 80 y 443
        ip saddr 172.20.0.0/24 ip daddr 172.21.0.10 tcp dport { 80, 443 } accept

        # DMZ → DMZ: proxy01 puede alcanzar web01
        ip saddr 172.21.0.10 ip daddr 172.21.0.20 accept

        # Bloquear acceso directo WAN → web01
        ip saddr 172.20.0.0/24 ip daddr 172.21.0.20 drop

        # DMZ no puede acceder a LAN
        ip saddr 172.21.0.0/24 ip daddr 192.168.100.0/24 drop
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }
}

table inet nat {
    chain prerouting {
        type nat hook prerouting priority -100;
    }
    chain postrouting {
        type nat hook postrouting priority 100;
        ip saddr 192.168.100.0/24 masquerade
    }
}
